//! The reference pages in `book/reference/` are generated, never written by
//! hand, so they cannot drift from the code:
//!
//! - `functions.md` from the one table of built-ins and task attributes that
//!   signature help and completion read (`runtime::services::BUILTINS`)
//! - `libraries.md` from what `import(id)` gives a note for each bundled
//!   library, with each export's parameters and `//` comment from its source
//! - `queries.md` from the collections a query binds, with the fields and
//!   value kinds their records have across `lang/examples`
//!
//! A page that differs from what the code generates fails the test; rewrite
//! the pages with `UPDATE_SNAPSHOTS=1`.
use lang::eval::engine::Tier;
use lang::eval::modules::Collection;
use runtime::services::{BUILTINS, Signature};
use serde_json::Value;
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    path::{Path, PathBuf},
    process::Command,
};

const NOW: &str = "2026-09-16T14:00:00-04:00";

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
}

#[test]
fn reference_pages_are_current() {
    let pages = [
        ("functions.md", functions()),
        ("libraries.md", libraries()),
        ("queries.md", queries()),
    ];
    let update = std::env::var("UPDATE_SNAPSHOTS").is_ok_and(|v| !v.is_empty() && v != "0");
    let directory = repo().join("book/reference");
    let mut stale = Vec::new();
    for (name, generated) in pages {
        let path = directory.join(name);
        if update {
            std::fs::create_dir_all(&directory).unwrap();
            std::fs::write(&path, generated).unwrap();
        } else if std::fs::read_to_string(&path).ok().as_deref() != Some(&generated) {
            stale.push(name);
        }
    }
    assert!(
        stale.is_empty(),
        "book/reference is stale: {}\nRerun with UPDATE_SNAPSHOTS=1 and commit the pages.",
        stale.join(", ")
    );
}

/// `xmd query --help` names the same bindings a query can use.
#[test]
fn query_help_lists_every_binding() {
    let output = xmd(&repo(), &["query", "--help"]);
    let listed: BTreeSet<&str> = output
        .lines()
        .find_map(|line| line.strip_prefix("Bindings: "))
        .expect("no Bindings line in `xmd query --help`")
        .split(", ")
        .collect();
    assert_eq!(listed, bindings().iter().map(String::as_str).collect());
}

/// The docs app completes collection names from its own list, which has to
/// be the same one.
#[test]
fn docs_app_completes_every_binding() {
    let source =
        std::fs::read_to_string(repo().join("client/web/apps/docs/src/lib/completions.js"))
            .unwrap();
    let list = source
        .lines()
        .find_map(|line| line.strip_prefix("export const COLLECTIONS = ["))
        .expect("no COLLECTIONS list in completions.js");
    let mut listed: Vec<String> = list
        .trim_end_matches("];")
        .split(", ")
        .map(|name| name.trim_matches('"').to_string())
        .collect();
    listed.sort();
    assert_eq!(listed, bindings());
}

fn header(title: &str, source: &str) -> String {
    format!(
        "# {title}\n\n<!-- generated by cli/tests/reference.rs; do not edit -->\n\n\
         generated from {source}. [back to the book](../README.md)\n"
    )
}

fn functions() -> String {
    let mut page = header(
        "functions",
        "the table signature help and completion read, \
         `runtime/analysis/src/signature.rs`",
    );
    let mut sorted: Vec<&Signature> = BUILTINS.iter().collect();
    sorted.sort_by_key(|s| s.name);
    let sections = [
        ("built-ins", "what a note is written with"),
        (
            "toolkit",
            "the list and text plumbing a note reaches for once it needs it",
        ),
        (
            "task attributes",
            "written after a task, like `- [ ] Pack @due(tomorrow)`",
        ),
        ("module built-ins", "only `.xmd` module code can call these"),
    ];
    for (index, (title, intro)) in sections.into_iter().enumerate() {
        write!(page, "\n## {title}\n\n{intro}\n").unwrap();
        for signature in &sorted {
            let section = match (signature.name.starts_with('@'), signature.tier) {
                (true, _) => 2,
                (false, Tier::Note) => 0,
                (false, Tier::Toolkit) => 1,
                (false, Tier::Module) => 3,
            };
            if section != index {
                continue;
            }
            let params = signature.params.join(", ");
            write!(page, "\n### `{}({params})`\n\n", signature.name).unwrap();
            if section != 2 {
                writeln!(page, "returns {}\n", signature.result.as_str()).unwrap();
            }
            writeln!(page, "{}\n", signature.documentation).unwrap();
            writeln!(page, "`{}({})`", signature.name, signature.example).unwrap();
        }
    }
    page
}

fn libraries() -> String {
    let mut page = header(
        "libraries",
        "the bundled `kind: \"library\"` modules in `lang/stdlib`. \
         `lib := import(\"id\")` gives a note the functions below",
    );
    let stdlib = repo().join("lang/stdlib");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&stdlib)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|e| e == "xmd"))
        .collect();
    files.sort();
    let workspace = tempfile::tempdir().unwrap();
    std::fs::write(workspace.path().join("probe.x.md"), "x := 1\n").unwrap();
    for file in files {
        let source = std::fs::read_to_string(&file).unwrap();
        if !source.contains("kind: \"library\"") {
            continue;
        }
        let id = file.file_stem().unwrap().to_string_lossy().into_owned();
        let output = xmd(
            workspace.path(),
            &[
                "probe.x.md",
                &format!("entries(import(\"{id}\")) | map(.key)"),
                "--json",
            ],
        );
        // A library the engine calls by name gives a note nothing to import.
        if output.contains("exports nothing") {
            continue;
        }
        let exports: Vec<String> = serde_json::from_str(&output)
            .unwrap_or_else(|e| panic!("import(\"{id}\") failed: {e}\n{output}"));
        write!(page, "\n## {id}\n\n`{id} := import(\"{id}\")`\n").unwrap();
        for name in exports {
            let (params, comment) = definition(&source, &name)
                .unwrap_or_else(|| panic!("{id} exports {name} but does not define it"));
            write!(page, "\n### `{id}.{name}{params}`\n").unwrap();
            assert!(
                !comment.is_empty(),
                "{id}.{name} has no `//` comment above it to describe it"
            );
            write!(page, "\n{comment}\n").unwrap();
        }
    }
    page
}

/// A definition's parameters, `(a, b)` for a function and empty for a value,
/// and the `//` comment above it. A comment above a run of one-line
/// definitions describes each of them.
fn definition(source: &str, name: &str) -> Option<(String, String)> {
    let lines: Vec<&str> = source.lines().collect();
    let at = lines
        .iter()
        .position(|line| line.starts_with(&format!("{name} := ")))?;
    let rest = &lines[at][name.len() + 4..];
    let params = match rest.strip_prefix("fn(") {
        Some(after) => format!("({})", &after[..after.find(')')?]),
        None => String::new(),
    };
    let group = lines[..at]
        .iter()
        .rev()
        .take_while(|line| line.contains(" := ") && !line.ends_with('('))
        .count();
    let mut comment: Vec<&str> = lines[..at - group]
        .iter()
        .rev()
        .map_while(|line| line.strip_prefix("//"))
        .map(str::trim)
        .collect();
    comment.reverse();
    Some((params, comment.join(" ")))
}

fn bindings() -> Vec<String> {
    let mut names: Vec<String> = Collection::names().split(", ").map(String::from).collect();
    names.push("graph".into());
    names.sort();
    names
}

fn queries() -> String {
    let mut page = header(
        "queries",
        "the collections a query binds by name. the fields are every field \
         the records have across `lang/examples`, with the kinds of value seen",
    );
    let examples = repo().join("lang/examples");
    for name in bindings() {
        write!(page, "\n## {name}\n").unwrap();
        let output = xmd(&examples, &["--workspace", &name, "--json"]);
        let rows: Vec<Value> = serde_json::from_str(&output)
            .unwrap_or_else(|e| panic!("`{name}` is not a JSON list: {e}"));
        let mut fields: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
        for row in &rows {
            for (field, value) in row.as_object().into_iter().flatten() {
                let kinds = fields.entry(field).or_default();
                if !value.is_null() {
                    kinds.insert(kind(value));
                }
            }
        }
        if fields.is_empty() {
            writeln!(page, "\nno example has one yet").unwrap();
            continue;
        }
        writeln!(page, "\n| field | value |\n| --- | --- |").unwrap();
        for (field, kinds) in fields {
            let kinds = if kinds.is_empty() {
                "always null".to_string()
            } else {
                kinds.into_iter().collect::<Vec<_>>().join(" or ")
            };
            writeln!(page, "| `{field}` | {kinds} |").unwrap();
        }
    }
    page
}

/// The kind of a JSON value as `--json` writes it: typed scalars carry their
/// `type`, the rest are plain JSON.
fn kind(value: &Value) -> &str {
    match value {
        Value::Object(object) => match object.get("type") {
            Some(Value::String(kind)) if object.contains_key("value") => kind,
            _ => "record",
        },
        Value::Array(_) => "list",
        Value::String(_) => "text",
        Value::Number(_) => "number",
        Value::Bool(_) => "boolean",
        Value::Null => "null",
    }
}

fn xmd(root: &Path, args: &[&str]) -> String {
    let config = tempfile::tempdir().unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_xmd"))
        .args(args)
        .arg("--root")
        .arg(root)
        .current_dir(root)
        .env("XDG_CONFIG_HOME", config.path())
        .env("XMD_NOW", NOW)
        .output()
        .unwrap();
    // `--help` takes no `--root`; its text comes back as an error then.
    let text = if output.status.success() {
        output.stdout
    } else {
        output.stderr
    };
    String::from_utf8(text).unwrap()
}
