id = "xmd"
name = "XMD"
version = "0.2.1"
schema_version = 1
authors = ["drbh"]
description = "Language support for XMD documents."
repository = "https://github.com/drbh/xmd"

[language_servers.xmd]
name = "XMD Language Server"
languages = ["XMD"]

[grammars.xmd]
repository = "https://github.com/drbh/xmd"
rev = "c09af46371d615735b1850d880baf9776d949bac"
path = "clients/ide/zed/grammar"
