// Generated by scripts/theme.mjs from palette.json.
export default [
  {
    "token": "variable.declaration",
    "foreground": "A8C7FA",
    "fontStyle": "bold"
  },
  {
    "token": "property.declaration",
    "foreground": "83D6CF",
    "fontStyle": "bold"
  },
  {
    "token": "wtfDepart.declaration",
    "foreground": "FFB070",
    "fontStyle": "bold"
  },
  {
    "token": "wtfArrive.declaration",
    "foreground": "9CE8A0",
    "fontStyle": "bold"
  },
  {
    "token": "wtfTransit.declaration",
    "foreground": "8FCBFF",
    "fontStyle": "bold"
  },
  {
    "token": "wtfStay.declaration",
    "foreground": "C9A4FF",
    "fontStyle": "bold"
  },
  {
    "token": "wtfMeal.declaration",
    "foreground": "FF8FA3",
    "fontStyle": "bold"
  },
  {
    "token": "wtfVisit.declaration",
    "foreground": "F6E38A",
    "fontStyle": "bold"
  },
  {
    "token": "wtfExplore.declaration",
    "foreground": "7FE3D0",
    "fontStyle": "bold"
  },
  {
    "token": "comment",
    "foreground": "889781",
    "fontStyle": "italic"
  },
  {
    "token": "keyword",
    "foreground": "F0A77D",
    "fontStyle": ""
  },
  {
    "token": "number",
    "foreground": "DABD90",
    "fontStyle": ""
  },
  {
    "token": "variable",
    "foreground": "A8C7FA",
    "fontStyle": ""
  },
  {
    "token": "function",
    "foreground": "C6A0F6",
    "fontStyle": ""
  },
  {
    "token": "property",
    "foreground": "83D6CF",
    "fontStyle": ""
  },
  {
    "token": "decorator",
    "foreground": "DEA2B8",
    "fontStyle": ""
  },
  {
    "token": "operator",
    "foreground": "EDB486",
    "fontStyle": ""
  },
  {
    "token": "string",
    "foreground": "CAD19B",
    "fontStyle": ""
  },
  {
    "token": "heading",
    "foreground": "D6E8C2",
    "fontStyle": "bold"
  },
  {
    "token": "wtfMoney",
    "foreground": "B4D98A",
    "fontStyle": "bold"
  },
  {
    "token": "wtfDate",
    "foreground": "F2B3DA",
    "fontStyle": "bold"
  },
  {
    "token": "wtfTime",
    "foreground": "91DCE8",
    "fontStyle": "bold"
  },
  {
    "token": "wtfDuration",
    "foreground": "F4BA7A",
    "fontStyle": ""
  },
  {
    "token": "wtfRatio",
    "foreground": "EAC080",
    "fontStyle": ""
  },
  {
    "token": "wtfBoolean",
    "foreground": "C6A0F6",
    "fontStyle": ""
  },
  {
    "token": "wtfPunctuation",
    "foreground": "85938B",
    "fontStyle": ""
  },
  {
    "token": "wtfCode",
    "foreground": "A1AE9B",
    "fontStyle": ""
  },
  {
    "token": "wtfLink",
    "foreground": "90BED8",
    "fontStyle": "underline"
  },
  {
    "token": "wtfCheckbox",
    "foreground": "FFD580",
    "fontStyle": "bold"
  },
  {
    "token": "wtfCheckboxChecked",
    "foreground": "91E6AC",
    "fontStyle": "bold"
  },
  {
    "token": "wtfTaskDone",
    "foreground": "87A788",
    "fontStyle": "strikethrough"
  },
  {
    "token": "wtfDay",
    "foreground": "FF9ECF",
    "fontStyle": "bold"
  },
  {
    "token": "wtfPlace",
    "foreground": "E2C4FF",
    "fontStyle": ""
  },
  {
    "token": "wtfDetailKey",
    "foreground": "9DB3A6",
    "fontStyle": "italic"
  },
  {
    "token": "wtfDepart",
    "foreground": "FFB070",
    "fontStyle": ""
  },
  {
    "token": "wtfArrive",
    "foreground": "9CE8A0",
    "fontStyle": ""
  },
  {
    "token": "wtfTransit",
    "foreground": "8FCBFF",
    "fontStyle": ""
  },
  {
    "token": "wtfStay",
    "foreground": "C9A4FF",
    "fontStyle": ""
  },
  {
    "token": "wtfMeal",
    "foreground": "FF8FA3",
    "fontStyle": ""
  },
  {
    "token": "wtfVisit",
    "foreground": "F6E38A",
    "fontStyle": ""
  },
  {
    "token": "wtfExplore",
    "foreground": "7FE3D0",
    "fontStyle": ""
  }
];
