// The neutral palette supplies HTML, Monaco, and the Zed adapter.
import { readFile, writeFile } from "node:fs/promises";
const theme = new URL("../theme/", import.meta.url);
const rules = JSON.parse(await readFile(new URL("palette.json", theme), "utf8"));
const css = rules.map(rule => {
  const selector = `.wtf .t-${rule.token_type}${(rule.token_modifiers || []).map(m => `.${m}`).join("")}`;
  const properties = [`color: ${rule.foreground_color}`];
  if (rule.font_weight) properties.push(`font-weight: ${rule.font_weight}`);
  if (rule.font_style) properties.push(`font-style: ${rule.font_style}`);
  if (rule.underline) properties.push("text-decoration-line: underline");
  if (rule.strikethrough) properties.push("text-decoration-line: line-through");
  return `${selector} { ${properties.join("; ")}; }`;
}).join("\n");
await writeFile(new URL("style.css", theme), `${await readFile(new URL("base.css", theme), "utf8")}\n${css}\n${await readFile(new URL("print.css", theme), "utf8")}`);
const monaco = rules.map(rule => ({
  token: [rule.token_type, ...(rule.token_modifiers || [])].join("."),
  foreground: rule.foreground_color.slice(1),
  fontStyle: [rule.font_weight === "bold" && "bold", rule.font_style, rule.underline && "underline", rule.strikethrough && "strikethrough"].filter(Boolean).join(" "),
}));
await writeFile(new URL("monaco.js", theme), `// Generated by scripts/theme.mjs from palette.json.\nexport default ${JSON.stringify(monaco, null, 2)};\n`);
await writeFile(new URL("../../ide/zed/languages/wtf/semantic_token_rules.json", import.meta.url), await readFile(new URL("palette.json", theme)));
