//! The book in `book/` is tested like code, so it cannot drift from it. This
//! is the guide to writing it; the book itself only talks to readers.
//!
//! Every chapter's fenced blocks run against the real binary in one shared
//! workspace, with the clock frozen and no user modules:
//!
//! - ```` ```xmd trip.x.md ```` writes a file into the workspace for later
//!   blocks and chapters to import or query; ```` ```xmd ```` alone is an
//!   anonymous note. Either kind must report no diagnostics.
//! - A word with `=` after the language is an option, never a file name.
//!   `off=highlight,results,controls` turns those off for the block on the
//!   site only, to build a feature up one block at a time; the test still
//!   checks the whole note. `active=chapter` turns a module block on for every
//!   note in its chapter, here through `.xmd/modules.json` before any of them
//!   render and on the page through `setModules`; its snapshot is the module
//!   as written.
//! - Each line of a ```` ```bash ```` block that runs `xmd` is a command, run
//!   with `sh` in the workspace. A trailing `#=> text` is its expected stdout.
//!   A ```` ```terminal weekend.x.md ```` block runs the same way; the site
//!   shows it as that note beside a terminal that ran them, where a reader
//!   can type more.
//!
//! What every block renders (`xmd render --format text`) and every command
//! prints is compared with `book/snapshots/<chapter>.txt`, so a change to the
//! language or the CLI shows up as a diff to the book. Never type a result
//! into the prose: put it in a block and let the snapshot hold it. Rewrite
//! the snapshots with `UPDATE_SNAPSHOTS=1`, and commit a chapter with its
//! snapshot.
//!
//! The site (`clients/web/scripts/lib/book.mjs`) turns the pages into
//! `dist/book/` and fails on a link to nothing;
//! `clients/web/tests/book.spec.mjs` checks the browser renders every block
//! as the snapshots record. `book/reference/` is generated by `reference.rs`.
mod support;

use std::{
    fmt::Write as _,
    path::{Path, PathBuf},
    process::Command,
};
use support::{NOW, isolate};

struct Chapter {
    name: String,
    blocks: Vec<Block>,
    /// Module files the chapter activates while its blocks run.
    modules: Vec<String>,
}

enum Block {
    Note {
        file: String,
    },
    /// A module the chapter activates: an active module is no note to query,
    /// and a broken one fails every note in the chapter instead.
    Module {
        file: String,
    },
    Commands(Vec<String>),
}

#[test]
fn book_runs_as_written() {
    let book = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../book");
    let workspace = tempfile::tempdir().unwrap();
    let root = workspace.path().canonicalize().unwrap();
    let config = tempfile::tempdir().unwrap();
    let chapters = load(&book, &root);
    assert!(!chapters.is_empty(), "no chapters in {}", book.display());

    let update = support::update_snapshots();
    let run = |args: &[&str]| {
        let mut command = Command::new(env!("CARGO_BIN_EXE_xmd"));
        command.args(args).current_dir(&root);
        isolate(&mut command, config.path(), NOW).output().unwrap()
    };
    let binary = Path::new(env!("CARGO_BIN_EXE_xmd")).parent().unwrap();
    let path = format!(
        "{}:{}",
        binary.display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let mut failures = Vec::new();
    let manifest = root.join(".xmd/modules.json");
    for chapter in &chapters {
        if chapter.modules.is_empty() {
            let _ = std::fs::remove_file(&manifest);
        } else {
            let paths: Vec<String> = chapter.modules.iter().map(|m| format!("../{m}")).collect();
            std::fs::create_dir_all(manifest.parent().unwrap()).unwrap();
            std::fs::write(&manifest, serde_json::to_string(&paths).unwrap()).unwrap();
        }
        let mut transcript = String::new();
        for block in &chapter.blocks {
            match block {
                Block::Module { file } => {
                    writeln!(transcript, "=== {file}").unwrap();
                    transcript.push_str(&std::fs::read_to_string(root.join(file)).unwrap());
                }
                Block::Note { file } => {
                    let output = run(&["query", file, "diagnostics | map(.message)", "--json"]);
                    let diagnostics = String::from_utf8_lossy(&output.stdout);
                    if !output.status.success() || diagnostics.trim() != "[]" {
                        failures.push(format!(
                            "{}: {file} reports diagnostics:\n{diagnostics}{}",
                            chapter.name,
                            String::from_utf8_lossy(&output.stderr)
                        ));
                    }
                    let output = run(&["render", file, "--format", "text"]);
                    writeln!(transcript, "=== {file}").unwrap();
                    transcript.push_str(&String::from_utf8_lossy(&output.stdout));
                }
                Block::Commands(commands) => {
                    for command in commands {
                        let mut sh = Command::new("sh");
                        sh.arg("-c").arg(command).current_dir(&root);
                        sh.env("PATH", &path);
                        let output = isolate(&mut sh, config.path(), NOW).output().unwrap();
                        let stdout = String::from_utf8_lossy(&output.stdout);
                        writeln!(transcript, "=== $ {command}").unwrap();
                        transcript.push_str(&stdout);
                        transcript.push_str(&String::from_utf8_lossy(&output.stderr));
                        if let Some(code) = output.status.code().filter(|&c| c != 0) {
                            writeln!(transcript, "[exit {code}]").unwrap();
                        }
                        if let Some((_, expected)) = command.split_once("#=>")
                            && stdout.trim() != expected.trim()
                        {
                            failures.push(format!(
                                "{}: `{command}` printed {:?}",
                                chapter.name,
                                stdout.trim()
                            ));
                        }
                    }
                }
            }
        }
        if transcript.is_empty() {
            continue;
        }
        let transcript = transcript.replace(&root.display().to_string(), "<root>");
        let snapshot = book.join("snapshots").join(format!("{}.txt", chapter.name));
        let expected = std::fs::read_to_string(&snapshot);
        if update {
            std::fs::create_dir_all(snapshot.parent().unwrap()).unwrap();
            std::fs::write(&snapshot, &transcript).unwrap();
        } else if let Ok(expected) = expected {
            if expected != transcript {
                failures.push(format!(
                    "{}: output differs from {}\n{}",
                    chapter.name,
                    snapshot.display(),
                    first_difference(&expected, &transcript)
                ));
            }
        } else {
            failures.push(format!(
                "{}: no snapshot at {}",
                chapter.name,
                snapshot.display()
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{}\nRerun with UPDATE_SNAPSHOTS=1 to accept output changes.",
        failures.join("\n\n")
    );
}

/// Reads the chapters in order and writes every note block into `root`.
fn load(book: &Path, root: &Path) -> Vec<Chapter> {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(book)
        .unwrap()
        .filter_map(|entry| Some(entry.ok()?.path()))
        .filter(|path| {
            let name = path.file_name().unwrap().to_string_lossy();
            name.ends_with(".md") && name.starts_with(|c: char| c.is_ascii_digit())
        })
        .collect();
    paths.sort();
    paths
        .iter()
        .map(|path| {
            let name = path.file_stem().unwrap().to_string_lossy().into_owned();
            let text = std::fs::read_to_string(path).unwrap();
            let mut modules = Vec::new();
            let blocks = fences(&text)
                .into_iter()
                .enumerate()
                .filter_map(|(index, (info, body))| {
                    let mut words = info.split_whitespace();
                    match words.next()? {
                        "xmd" => {
                            let words: Vec<&str> = words.collect();
                            // `off=…` only changes how the site draws the block.
                            let file = match words.iter().find(|word| !word.contains('=')) {
                                Some(file) => file.to_string(),
                                None => format!("{name}-{}.x.md", index + 1),
                            };
                            let target = root.join(&file);
                            assert!(!target.exists(), "{name}: {file} is written twice");
                            std::fs::create_dir_all(target.parent().unwrap()).unwrap();
                            std::fs::write(&target, body).unwrap();
                            if words.contains(&"active=chapter") {
                                modules.push(file.clone());
                                return Some(Block::Module { file });
                            }
                            Some(Block::Note { file })
                        }
                        // A terminal is a note and the commands typed beside it.
                        "bash" | "terminal" => Some(Block::Commands(
                            body.lines()
                                .map(str::trim)
                                .filter(|line| !line.starts_with('#') && line.contains("xmd"))
                                .map(String::from)
                                .collect(),
                        )),
                        _ => None,
                    }
                })
                .collect();
            Chapter {
                name,
                blocks,
                modules,
            }
        })
        .collect()
}

/// The fenced blocks of a markdown page as (info string, body).
fn fences(text: &str) -> Vec<(String, String)> {
    let mut blocks = Vec::new();
    let mut open: Option<(String, String)> = None;
    for line in text.lines() {
        match (&mut open, line.strip_prefix("```")) {
            (None, Some(info)) => open = Some((info.trim().to_string(), String::new())),
            (Some(_), Some(_)) => blocks.push(open.take().unwrap()),
            (Some((_, body)), None) => {
                body.push_str(line);
                body.push('\n');
            }
            (None, None) => {}
        }
    }
    blocks
}

fn first_difference(expected: &str, actual: &str) -> String {
    let mut expected_lines = expected.lines();
    let mut actual_lines = actual.lines();
    for number in 1.. {
        match (expected_lines.next(), actual_lines.next()) {
            (None, None) => break,
            (e, a) if e == a => continue,
            (e, a) => {
                return format!(
                    "line {number}\n  expected: {}\n  actual:   {}",
                    e.unwrap_or("<end>"),
                    a.unwrap_or("<end>")
                );
            }
        }
    }
    String::new()
}
