//! The reference pages in `book/reference/` are generated, never written by
//! hand, so they cannot drift from the code:
//!
//! - `functions.md` from the one table of built-ins that signature help and
//!   completion read (`services::BUILTINS`), the prelude's functions
//!   as they read them (`Workspace::prelude_functions`), and the attributes
//!   the bundled modules declare, which they read beside it
//! - `libraries.md` from what `import(id)` gives a note for each bundled
//!   library, with each export's parameters and `//` comment from its source
//! - `queries.md` from the collections a query binds, with the fields and
//!   value kinds their records have across `examples`
//! - `contract.md` from what native code calls in the stdlib
//!   (`lang::stdlib::CONTRACT`), the hooks it calls on modules
//!   (`lang::eval::modules::HOOKS`) and the `step` loops of commands and
//!   providers (`STEPS`, with the host's limits)
//!
//! A page that differs from what the code generates fails the test; rewrite
//! the pages with `UPDATE_SNAPSHOTS=1`.
use lang::eval::engine::Tier;
use lang::eval::modules::Collection;
use serde_json::Value;
use services::{BUILTINS, Signature};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    path::{Path, PathBuf},
    process::Command,
};

const NOW: &str = "2026-09-16T14:00:00-04:00";

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

#[test]
fn reference_pages_are_current() {
    let pages = [
        ("functions.md", functions()),
        ("libraries.md", libraries()),
        ("queries.md", queries()),
        ("contract.md", contract()),
    ];
    let update = std::env::var("UPDATE_SNAPSHOTS").is_ok_and(|v| !v.is_empty() && v != "0");
    let directory = repo().join("book/reference");
    let mut stale = Vec::new();
    for (name, generated) in pages {
        let path = directory.join(name);
        if update {
            std::fs::create_dir_all(&directory).unwrap();
            std::fs::write(&path, generated).unwrap();
        } else if std::fs::read_to_string(&path).ok().as_deref() != Some(&generated) {
            stale.push(name);
        }
    }
    assert!(
        stale.is_empty(),
        "book/reference is stale: {}\nRerun with UPDATE_SNAPSHOTS=1 and commit the pages.",
        stale.join(", ")
    );
}

/// `xmd query --help` names the same bindings a query can use.
#[test]
fn query_help_lists_every_binding() {
    let output = xmd(&repo(), &["query", "--help"]);
    let listed: BTreeSet<&str> = output
        .lines()
        .find_map(|line| line.strip_prefix("Bindings: "))
        .expect("no Bindings line in `xmd query --help`")
        .split(", ")
        .collect();
    assert_eq!(listed, bindings().iter().map(String::as_str).collect());
}

/// The docs app completes collection names from its own list, which has to
/// be the same one.
#[test]
fn docs_app_completes_every_binding() {
    let source =
        std::fs::read_to_string(repo().join("clients/web/apps/docs/src/lib/completions.js"))
            .unwrap();
    let list = source
        .lines()
        .find_map(|line| line.strip_prefix("export const COLLECTIONS = ["))
        .expect("no COLLECTIONS list in completions.js");
    let mut listed: Vec<String> = list
        .trim_end_matches("];")
        .split(", ")
        .map(|name| name.trim_matches('"').to_string())
        .collect();
    listed.sort();
    assert_eq!(listed, bindings());
}

fn header(title: &str, source: &str) -> String {
    format!(
        "# {title}\n\n<!-- generated by hosts/cli/tests/reference.rs; do not edit -->\n\n\
         generated from {source}. [back to the book](../README.md)\n"
    )
}

/// One entry of `functions.md`: a built-in's row, or an attribute a
/// bundled module declares.
struct Row<'a> {
    name: String,
    params: Vec<&'a str>,
    result: &'a str,
    documentation: &'a str,
    example: &'a str,
    tier: Tier,
}

fn functions() -> String {
    let mut page = header(
        "functions",
        "the table signature help and completion read, \
         `services/analysis/src/signature.rs`, and the functions of the prelude \
         library, `stdlib/prelude.xmd`, from their `//` comments",
    );
    let workspace = lang::eval::Workspace::new(vec![]);
    let recognizers = workspace.modules().recognizers();
    let declared = recognizers.attributes;
    let rows = BUILTINS
        .iter()
        .map(|s: &Signature| Row {
            name: s.name.to_owned(),
            params: s.params.to_vec(),
            result: s.result.as_str(),
            documentation: s.documentation,
            example: s.example,
            tier: s.tier,
        })
        // A form a bundled module declares is written like a built-in.
        .chain(recognizers.forms.iter().map(|f| Row {
            name: f.name.clone(),
            params: f.params.iter().map(String::as_str).collect(),
            result: &f.returns,
            documentation: &f.documentation,
            example: &f.example,
            tier: Tier::Note,
        }))
        .chain(declared.iter().map(|d| Row {
            name: format!("@{}", d.key),
            params: d.params.iter().map(String::as_str).collect(),
            result: &d.applies,
            documentation: &d.documentation,
            example: &d.example,
            tier: Tier::Note,
        }));
    let sections = [
        (
            "built-ins",
            "what a note is written with. the ones marked *prelude* are .xmd \
             functions every note can call by name, below the names it defines itself",
        ),
        (
            "toolkit",
            "the list and text plumbing a note reaches for once it needs it",
        ),
        (
            "attributes",
            "written on a line, like `- [ ] Pack @due(tomorrow)`. the bundled \
             module that owns each one declares it: `tasks` a task's, \
             `appointments` an appointment's `@at`",
        ),
        ("module built-ins", "only `.xmd` module code can call these"),
    ];
    // Each entry as (section, name, text), sorted by name within a section.
    let mut entries: Vec<(usize, String, String)> = rows
        .map(|row| {
            let section = match (row.name.starts_with('@'), row.tier) {
                (true, _) => 2,
                (false, Tier::Note) => 0,
                (false, Tier::Toolkit) => 1,
                (false, Tier::Module) => 3,
            };
            let params = row.params.join(", ");
            let mut text = format!("\n### `{}({params})`\n\n", row.name);
            if section != 2 {
                writeln!(text, "returns {}\n", row.result).unwrap();
            }
            writeln!(text, "{}\n", row.documentation).unwrap();
            writeln!(text, "`{}({})`", row.name, row.example).unwrap();
            (section, row.name, text)
        })
        .collect();
    for function in workspace.prelude_functions() {
        let text = format!(
            "\n### `{}({})`\n\n*prelude*\n\n{}\n",
            function.name,
            function.params.join(", "),
            function.documentation
        );
        entries.push((0, function.name, text));
    }
    entries.sort_by(|a, b| a.1.cmp(&b.1));
    for (index, (title, intro)) in sections.into_iter().enumerate() {
        write!(page, "\n## {title}\n\n{intro}\n").unwrap();
        for (_, _, text) in entries.iter().filter(|(section, ..)| *section == index) {
            page.push_str(text);
        }
    }
    page
}

fn libraries() -> String {
    let mut page = header(
        "libraries",
        "the bundled `kind: \"library\"` modules in `stdlib`. \
         `lib := import(\"id\")` gives a note the functions below",
    );
    let stdlib = repo().join("stdlib");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&stdlib)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|e| e == "xmd"))
        .collect();
    files.sort();
    let workspace = tempfile::tempdir().unwrap();
    std::fs::write(workspace.path().join("probe.x.md"), "x := 1\n").unwrap();
    for file in files {
        let source = std::fs::read_to_string(&file).unwrap();
        if !source.contains("kind: \"library\"") {
            continue;
        }
        let id = file.file_stem().unwrap().to_string_lossy().into_owned();
        let output = xmd(
            workspace.path(),
            &[
                "probe.x.md",
                &format!("entries(import(\"{id}\")) | map(.key)"),
                "--json",
            ],
        );
        // A library the engine calls by name gives a note nothing to import.
        if output.contains("exports nothing") {
            continue;
        }
        let exports: Vec<String> = serde_json::from_str(&output)
            .unwrap_or_else(|e| panic!("import(\"{id}\") failed: {e}\n{output}"));
        write!(page, "\n## {id}\n\n`{id} := import(\"{id}\")`\n").unwrap();
        for name in exports {
            let (params, comment) = definition(&source, &name)
                .unwrap_or_else(|| panic!("{id} exports {name} but does not define it"));
            write!(page, "\n### `{id}.{name}{params}`\n").unwrap();
            assert!(
                !comment.is_empty(),
                "{id}.{name} has no `//` comment above it to describe it"
            );
            write!(page, "\n{comment}\n").unwrap();
        }
    }
    page
}

/// A definition's parameters, `(a, b)` for a function and empty for a value,
/// and the `//` comment above it. A comment above a run of one-line
/// definitions describes each of them.
fn definition(source: &str, name: &str) -> Option<(String, String)> {
    let lines: Vec<&str> = source.lines().collect();
    let at = lines
        .iter()
        .position(|line| line.starts_with(&format!("{name} := ")))?;
    let rest = &lines[at][name.len() + 4..];
    let params = match rest.strip_prefix("fn(") {
        Some(after) => format!("({})", &after[..after.find(')')?]),
        None => String::new(),
    };
    let group = lines[..at]
        .iter()
        .rev()
        .take_while(|line| line.contains(" := ") && !line.ends_with('('))
        .count();
    let mut comment: Vec<&str> = lines[..at - group]
        .iter()
        .rev()
        .map_while(|line| line.strip_prefix("//"))
        .map(str::trim)
        .collect();
    comment.reverse();
    Some((params, comment.join(" ")))
}

/// Every name a query binds: the native collections, `graph`, and the
/// collections the bundled modules declare.
fn bindings() -> Vec<String> {
    let mut names: Vec<String> = Collection::names().split(", ").map(String::from).collect();
    names.push("graph".into());
    let workspace = lang::eval::Workspace::new(vec![]);
    names.extend(
        workspace
            .modules()
            .declared()
            .map(|(_, declared)| declared.name.to_string()),
    );
    names.sort();
    names
}

fn queries() -> String {
    let mut page = header(
        "queries",
        "the collections a query binds by name. the fields are every field \
         the records have across `examples`, with the kinds of value seen",
    );
    let examples = repo().join("examples");
    for name in bindings() {
        write!(page, "\n## {name}\n").unwrap();
        let output = xmd(&examples, &["--workspace", &name, "--json"]);
        let rows: Vec<Value> = serde_json::from_str(&output)
            .unwrap_or_else(|e| panic!("`{name}` is not a JSON list: {e}"));
        let mut fields: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
        for row in &rows {
            for (field, value) in row.as_object().into_iter().flatten() {
                let kinds = fields.entry(field).or_default();
                if !value.is_null() {
                    kinds.insert(kind(value));
                }
            }
        }
        if fields.is_empty() {
            writeln!(page, "\nno example has one yet").unwrap();
            continue;
        }
        writeln!(page, "\n| field | value |\n| --- | --- |").unwrap();
        for (field, kinds) in fields {
            let kinds = if kinds.is_empty() {
                "always null".to_string()
            } else {
                kinds.into_iter().collect::<Vec<_>>().join(" or ")
            };
            writeln!(page, "| `{field}` | {kinds} |").unwrap();
        }
    }
    page
}

fn contract() -> String {
    use lang::eval::modules::{HOOK_RECORDS, HOOKS, Hook, ModuleKind, STEPS};
    use lang::stdlib::{CONTRACT, Role};

    let mut page = header(
        "contract",
        "`core/eval/src/contract.rs` for what native code calls in the \
         stdlib, and the hook and `step` declarations in \
         `core/modules/src/module.rs` for what it calls on a module",
    );
    page.push_str(
        "\nnative code and the .xmd modules meet in three directions. native code \
         calls stdlib functions by name, the host calls the hooks of feature, link, \
         command and provider modules, and module code calls built-ins\n",
    );

    write!(
        page,
        "\n## native calls the stdlib\n\n\
         the functions the engine, the language services and the editors call in a \
         bundled module. a module that replaces a bundled id is checked against \
         this list when the registry links: it has to define every required \
         function. an optional one falls back to native code when it is absent\n\n\
         **presents** is words or markup for a person, so a failure costs only a \
         label: the person sees the neutral stand-in under *if it fails* where \
         the words go, and when the workspace brings its own modules the note \
         carries a `module` warning naming the function and the error on the \
         first thing it failed for. **decides** is behavior the engine or an \
         editor acts on, so a failure reaches the person as a diagnostic, an \
         error or a disabled control that says why, never as a quiet default\n"
    )
    .unwrap();
    let mut modules: Vec<&str> = Vec::new();
    for entry in CONTRACT {
        if !modules.contains(&entry.module) {
            modules.push(entry.module);
        }
    }
    for module in modules {
        write!(
            page,
            "\n### {module}\n\n| function | returns | role | if it fails | what it is |\n| --- | --- | --- | --- | --- |\n"
        )
        .unwrap();
        for entry in CONTRACT.iter().filter(|e| e.module == module) {
            let (role, fails) = match entry.role {
                Role::Presents { fallback } => ("presents", format!("shows {fallback}")),
                Role::Decides => ("decides", "reported".to_owned()),
            };
            let optional = if entry.required { "" } else { ", optional" };
            writeln!(
                page,
                "| `{module}.{}({})` | {} | {role}{optional} | {} | {} |",
                entry.function,
                entry.params.join(", "),
                cell(entry.returns),
                cell(&fails),
                cell(entry.doc),
            )
            .unwrap();
        }
    }

    write!(
        page,
        "\n## hooks\n\n\
         the fixed functions the host calls on a module, by kind. a library has \
         none: its exports are its own names. a module that defines a hook has to \
         define it as a function of exactly these parameters. a shape in lowercase \
         is one of the records below, or a step's input or output under commands \
         and providers\n\n### records\n"
    )
    .unwrap();
    for record in HOOK_RECORDS {
        write!(
            page,
            "\n#### {}\n\n{}\n\n| field | what it is |\n| --- | --- |\n",
            record.name, record.doc
        )
        .unwrap();
        for (field, doc) in record
            .fields
            .iter()
            .map(|f| f.split_once(": ").expect("name: meaning"))
        {
            writeln!(page, "| `{field}` | {} |", cell(doc)).unwrap();
        }
    }
    // Kinds with the same hooks share a section: commands and providers.
    let kinds: BTreeSet<ModuleKind> = HOOKS.iter().flat_map(|h| h.kinds).copied().collect();
    let mut groups: Vec<(Vec<ModuleKind>, Vec<Hook>)> = Vec::new();
    for kind in &kinds {
        let hooks: Vec<Hook> = HOOKS
            .iter()
            .filter(|h| h.kinds.contains(kind))
            .map(|h| h.hook)
            .collect();
        if hooks.is_empty() {
            continue;
        }
        match groups.iter_mut().find(|(_, h)| *h == hooks) {
            Some((kinds, _)) => kinds.push(*kind),
            None => groups.push((vec![*kind], hooks)),
        }
    }
    for (kinds, hooks) in groups {
        let names: Vec<String> = kinds.iter().map(ToString::to_string).collect();
        write!(page, "\n### {} modules\n", names.join(" and ")).unwrap();
        for hook in hooks {
            let contract = hook.contract();
            write!(
                page,
                "\n#### `{hook}({})`\n\nreturns {}\n\n{}\n",
                contract.params.join(", "),
                contract.returns,
                contract.doc
            )
            .unwrap();
        }
    }

    write!(
        page,
        "\n## commands and providers\n\n\
         a command or provider module is one pure `step` hook in a loop. each step \
         returns the effects it wants as `requests`, the host performs them, and \
         the next step reads their results. every result has `ok`: a failed effect \
         answers `{{ok: false, error}}` rather than stopping the loop, so the module \
         decides what a failure means\n"
    )
    .unwrap();
    for protocol in STEPS {
        write!(page, "\n### {}\n\n{}\n", protocol.kind, protocol.doc).unwrap();
        let limits = match protocol.kind {
            ModuleKind::Command => format!(
                "a step may request at most {} effects, and a run that has not \
                 finished in {} steps stops",
                native::MAX_REQUESTS,
                native::MAX_STEPS
            ),
            _ => format!(
                "a lookup that has not finished in {} steps fails",
                native::PROVIDER_STEPS
            ),
        };
        writeln!(page, "\n{limits}").unwrap();
        for (title, fields) in [("input", protocol.input), ("output", protocol.output)] {
            write!(
                page,
                "\n#### {title}\n\n| field | what it is |\n| --- | --- |\n"
            )
            .unwrap();
            for (field, doc) in fields
                .iter()
                .map(|f| f.split_once(": ").expect("name: meaning"))
            {
                writeln!(page, "| `{field}` | {} |", cell(doc)).unwrap();
            }
        }
        write!(
            page,
            "\n#### effects\n\n| kind | request | answer | what it does |\n| --- | --- | --- | --- |\n"
        )
        .unwrap();
        for effect in protocol.effects {
            writeln!(
                page,
                "| `{}` | {} | {} | {} |",
                effect.kind,
                cell(effect.request),
                cell(effect.answer),
                cell(effect.doc)
            )
            .unwrap();
        }
    }

    page.push_str(
        "\n## the stdlib calls native\n\n\
         module code calls the module built-ins in [functions](functions.md), and \
         reads the collections in [queries](queries.md)\n",
    );
    page
}

/// Text in a table cell, its pipes escaped.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

/// The kind of a JSON value as `--json` writes it: typed scalars carry their
/// `type`, the rest are plain JSON.
fn kind(value: &Value) -> &str {
    match value {
        Value::Object(object) => match object.get("type") {
            Some(Value::String(kind)) if object.contains_key("value") => kind,
            _ => "record",
        },
        Value::Array(_) => "list",
        Value::String(_) => "text",
        Value::Number(_) => "number",
        Value::Bool(_) => "boolean",
        Value::Null => "null",
    }
}

fn xmd(root: &Path, args: &[&str]) -> String {
    let config = tempfile::tempdir().unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_xmd"))
        .args(args)
        .arg("--root")
        .arg(root)
        .current_dir(root)
        .env("XDG_CONFIG_HOME", config.path())
        .env("XMD_NOW", NOW)
        .output()
        .unwrap();
    // `--help` takes no `--root`; its text comes back as an error then.
    let text = if output.status.success() {
        output.stdout
    } else {
        output.stderr
    };
    String::from_utf8(text).unwrap()
}

/// The bundled modules meet the whole stdlib contract: every module id it
/// names is bundled, and compiling the bundled set alone (which checks each
/// contract function's presence and arity) reports no problem.
#[test]
fn bundled_stdlib_meets_the_contract() {
    use lang::eval::modules::{CompileModules, ModuleRegistry};
    let registry = ModuleRegistry::compile(BTreeMap::new())
        .unwrap_or_else(|problems| panic!("the bundled stdlib breaks its contract:\n{problems}"));
    for entry in lang::stdlib::CONTRACT {
        let module = registry.get(entry.module).unwrap_or_else(|| {
            panic!(
                "the contract names '{}', which is not bundled",
                entry.module
            )
        });
        assert!(
            module
                .member_names()
                .iter()
                .any(|name| name == entry.function),
            "{}.{} is in the contract but not bundled",
            entry.module,
            entry.function
        );
    }
}
