//! The reference pages in `book/reference/` are generated, never written by
//! hand, so they cannot drift from the code:
//!
//! - `functions.md` from the one table of built-ins that signature help and
//!   completion read (`services::BUILTINS`), the prelude's functions
//!   as they read them (`Workspace::prelude_functions`), and the attributes
//!   the bundled modules declare, which they read beside it
//! - `libraries.md` from what `import(id)` gives a note for each bundled
//!   library, with each export's parameters and `//` comment from its source
//! - `collections.md` from `core/values/data/collections.md`: each collection
//!   a query binds, an example command run on `examples` with its output, and
//!   a description of every field its records have there. A field with no
//!   description, or a description of a field no record has, fails the test
//! - `writing-modules.md` from `core/modules/data/kinds.md`, laid out over the
//!   hooks, records and `step` loops of `core/modules/data/hooks.md` and what
//!   native code calls in the stdlib (`lang::stdlib::CONTRACT`). Every example
//!   module compiles, and every record is shown under a kind
//!
//! A page that differs from what the code generates fails the test; rewrite
//! the pages with `UPDATE_SNAPSHOTS=1`.
mod support;

use lang::eval::modules::Collection;
use lang::syntax::Tier;
use serde_json::Value;
use services::{BUILTINS, Signature};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    path::{Path, PathBuf},
    process::Command,
};

fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

#[test]
fn reference_pages_are_current() {
    let pages = [
        ("functions.md", functions()),
        ("libraries.md", libraries()),
        ("collections.md", collections()),
        ("writing-modules.md", writing_modules()),
    ];
    let update = support::update_snapshots();
    let directory = repo().join("book/reference");
    let mut stale = Vec::new();
    for (name, generated) in pages {
        let path = directory.join(name);
        if update {
            std::fs::create_dir_all(&directory).unwrap();
            std::fs::write(&path, generated).unwrap();
        } else if std::fs::read_to_string(&path).ok().as_deref() != Some(&generated) {
            stale.push(name);
        }
    }
    assert!(
        stale.is_empty(),
        "book/reference is stale: {}\nRerun with UPDATE_SNAPSHOTS=1 and commit the pages.",
        stale.join(", ")
    );
}

/// `xmd query --help` names the same bindings a query can use.
#[test]
fn query_help_lists_every_binding() {
    let output = xmd(&repo(), &["query", "--help"]);
    let listed: BTreeSet<&str> = output
        .lines()
        .find_map(|line| line.strip_prefix("Bindings: "))
        .expect("no Bindings line in `xmd query --help`")
        .split(", ")
        .collect();
    assert_eq!(listed, bindings().iter().map(String::as_str).collect());
}

/// The docs app completes collection names from its own list, which has to
/// be the same one.
#[test]
fn docs_app_completes_every_binding() {
    let source =
        std::fs::read_to_string(repo().join("clients/web/apps/docs/src/lib/completions.js"))
            .unwrap();
    let list = source
        .lines()
        .find_map(|line| line.strip_prefix("export const COLLECTIONS = ["))
        .expect("no COLLECTIONS list in completions.js");
    let mut listed: Vec<String> = list
        .trim_end_matches("];")
        .split(", ")
        .map(|name| name.trim_matches('"').to_string())
        .collect();
    listed.sort();
    assert_eq!(listed, bindings());
}

/// A page's title and what it is for, in the reader's terms: where it comes
/// from is this file's business, in the comment readers never see.
fn header(title: &str, intro: &str) -> String {
    format!(
        "# {title}\n\n<!-- generated by hosts/cli/tests/reference.rs; do not edit -->\n\n\
         {intro}. [back to the book](../README.md)\n"
    )
}

/// One entry of `functions.md`: a built-in's row, or an attribute a
/// bundled module declares.
struct Row<'a> {
    name: String,
    params: Vec<&'a str>,
    result: &'a str,
    documentation: &'a str,
    example: &'a str,
    tier: Tier,
}

fn functions() -> String {
    let mut page = header(
        "functions",
        "every function a note can call without an import, and every task \
         attribute. your editor's completion and signature help show the same \
         descriptions as you type",
    );
    let workspace = lang::eval::Workspace::new(vec![]);
    let recognizers = workspace.modules().recognizers();
    let declared = recognizers.attributes;
    let rows = BUILTINS
        .iter()
        .map(|s: &Signature| Row {
            name: s.name.to_owned(),
            params: s.params.to_vec(),
            result: s.result.as_str(),
            documentation: s.documentation,
            example: s.example,
            tier: s.tier,
        })
        // A form a bundled module declares is written like a built-in.
        .chain(recognizers.forms.iter().map(|f| Row {
            name: f.name.clone(),
            params: f.params.iter().map(String::as_str).collect(),
            result: &f.returns,
            documentation: &f.documentation,
            example: &f.example,
            tier: Tier::Note,
        }))
        .chain(declared.iter().map(|d| Row {
            name: format!("@{}", d.key),
            params: d.params.iter().map(String::as_str).collect(),
            result: &d.applies,
            documentation: &d.documentation,
            example: &d.example,
            tier: Tier::Note,
        }));
    let sections = [
        (
            "built-ins",
            "what a note is written with. the ones marked *prelude* are .xmd \
             functions every note can call by name, below the names it defines itself",
        ),
        (
            "toolkit",
            "the list and text plumbing a note reaches for once it needs it",
        ),
        (
            "attributes",
            "written on a line, like `- [ ] Pack @due(tomorrow)`. the bundled \
             module that owns each one declares it: `tasks` a task's, \
             `appointments` an appointment's `@at`",
        ),
        ("module built-ins", "only `.xmd` module code can call these"),
    ];
    // Each entry as (section, name, text), sorted by name within a section.
    let mut entries: Vec<(usize, String, String)> = rows
        .map(|row| {
            let section = match (row.name.starts_with('@'), row.tier) {
                (true, _) => 2,
                (false, Tier::Note) => 0,
                (false, Tier::Toolkit) => 1,
                (false, Tier::Module) => 3,
            };
            let params = row.params.join(", ");
            let mut text = format!("\n### `{}({params})`\n\n", row.name);
            if section != 2 {
                let _ = writeln!(text, "returns {}\n", row.result);
            }
            let _ = writeln!(text, "{}\n", row.documentation);
            let _ = writeln!(text, "`{}({})`", row.name, row.example);
            (section, row.name, text)
        })
        .collect();
    for function in workspace.prelude_functions() {
        let text = format!(
            "\n### `{}({})`\n\n*prelude*\n\n{}\n",
            function.name,
            function.params.join(", "),
            function.documentation
        );
        entries.push((0, function.name, text));
    }
    entries.sort_by(|a, b| a.1.cmp(&b.1));
    for (index, (title, intro)) in sections.into_iter().enumerate() {
        let _ = write!(page, "\n## {title}\n\n{intro}\n");
        for (_, _, text) in entries.iter().filter(|(section, ..)| *section == index) {
            page.push_str(text);
        }
    }
    page
}

fn libraries() -> String {
    let mut page = header(
        "libraries",
        "the libraries every note can import. `lib := import(\"id\")` gives \
         a note the functions below",
    );
    let stdlib = repo().join("stdlib");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&stdlib)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|e| e == "xmd"))
        .collect();
    files.sort();
    let workspace = tempfile::tempdir().unwrap();
    std::fs::write(workspace.path().join("probe.x.md"), "x := 1\n").unwrap();
    for file in files {
        let source = std::fs::read_to_string(&file).unwrap();
        if !source.contains("kind: \"library\"") {
            continue;
        }
        let id = file.file_stem().unwrap().to_string_lossy().into_owned();
        let output = xmd(
            workspace.path(),
            &[
                "probe.x.md",
                &format!("entries(import(\"{id}\")) | map(.key)"),
                "--json",
            ],
        );
        // A library the engine calls by name gives a note nothing to import.
        if output.contains("exports nothing") {
            continue;
        }
        let exports: Vec<String> = serde_json::from_str(&output)
            .unwrap_or_else(|e| panic!("import(\"{id}\") failed: {e}\n{output}"));
        let _ = write!(page, "\n## {id}\n\n`{id} := import(\"{id}\")`\n");
        for name in exports {
            let (params, comment) = definition(&source, &name)
                .unwrap_or_else(|| panic!("{id} exports {name} but does not define it"));
            let _ = write!(page, "\n### `{id}.{name}{params}`\n");
            assert!(
                !comment.is_empty(),
                "{id}.{name} has no `//` comment above it to describe it"
            );
            let _ = write!(page, "\n{comment}\n");
        }
    }
    page
}

/// A definition's parameters, `(a, b)` for a function and empty for a value,
/// and the `//` comment above it. A comment above a run of one-line
/// definitions describes each of them.
fn definition(source: &str, name: &str) -> Option<(String, String)> {
    let lines: Vec<&str> = source.lines().collect();
    let at = lines
        .iter()
        .position(|line| line.starts_with(&format!("{name} := ")))?;
    let rest = &lines[at][name.len() + 4..];
    let params = match rest.strip_prefix("fn(") {
        Some(after) => format!("({})", &after[..after.find(')')?]),
        None => String::new(),
    };
    let group = lines[..at]
        .iter()
        .rev()
        .take_while(|line| line.contains(" := ") && !line.ends_with('('))
        .count();
    let mut comment: Vec<&str> = lines[..at - group]
        .iter()
        .rev()
        .map_while(|line| line.strip_prefix("//"))
        .map(str::trim)
        .collect();
    comment.reverse();
    Some((params, comment.join(" ")))
}

/// Every name a query binds: the native collections, `graph`, and the
/// collections the bundled modules declare.
fn bindings() -> Vec<String> {
    let mut names: Vec<String> = Collection::names().split(", ").map(String::from).collect();
    names.push("graph".into());
    let workspace = lang::eval::Workspace::new(vec![]);
    names.extend(
        workspace
            .modules()
            .declared()
            .map(|(_, declared)| declared.name.to_string()),
    );
    names.sort();
    names
}

/// A data file's `# part`s, each its title and the lines under it, blank
/// lines dropped.
fn parts(text: &str) -> Vec<(&str, Vec<&str>)> {
    text.split("\n# ")
        .skip(1)
        .map(|part| {
            let mut lines = part.lines();
            let title = lines.next().unwrap_or_default();
            (title, lines.filter(|l| !l.trim().is_empty()).collect())
        })
        .collect()
}

/// A part's lines up to its first `##` entry, and each entry's lines.
fn entries<'a>(lines: &[&'a str]) -> (Vec<&'a str>, Vec<(&'a str, Vec<&'a str>)>) {
    let mut head = Vec::new();
    let mut entries: Vec<(&str, Vec<&str>)> = Vec::new();
    for &line in lines {
        match (line.strip_prefix("## "), entries.last_mut()) {
            (Some(title), _) => entries.push((title, Vec::new())),
            (None, Some((_, body))) => body.push(line),
            (None, None) => head.push(line),
        }
    }
    (head, entries)
}

/// The `- name: meaning` lines among `lines`, in order.
fn described<'a>(lines: &[&'a str]) -> Vec<(&'a str, &'a str)> {
    lines
        .iter()
        .filter_map(|line| line.strip_prefix("- ")?.split_once(": "))
        .collect()
}

/// The prose lines among `lines`: not a field, an entry heading or a `key:`
/// line the generator reads.
fn prose<'a>(lines: &[&'a str]) -> Vec<&'a str> {
    let keys = ["example: ", "run: ", "records: "];
    lines
        .iter()
        .filter(|l| !l.starts_with("- ") && !keys.iter().any(|k| l.starts_with(k)))
        .copied()
        .collect()
}

/// The text after `key` on the first line that starts with it.
fn keyed<'a>(lines: &[&'a str], key: &str) -> Option<&'a str> {
    lines.iter().find_map(|line| line.strip_prefix(key))
}

/// What a shell command prints, run in `dir` with this build's `xmd` first on
/// the path. It has to succeed and print something, and never the machine's
/// own paths.
fn run(dir: &Path, command: &str) -> String {
    let config = tempfile::tempdir().unwrap();
    let binary = Path::new(env!("CARGO_BIN_EXE_xmd")).parent().unwrap();
    let path = format!(
        "{}:{}",
        binary.display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let mut sh = Command::new("sh");
    sh.arg("-c").arg(command).current_dir(dir).env("PATH", path);
    let output = support::isolate(&mut sh, config.path(), support::NOW)
        .output()
        .unwrap();
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(
        output.status.success() && !stdout.trim().is_empty(),
        "`{command}` failed:\n{stdout}{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let root = repo().canonicalize().unwrap();
    assert!(
        !stdout.contains(&*root.to_string_lossy()),
        "`{command}` prints a path on this machine"
    );
    stdout
}

/// An example command and what it prints.
fn example(page: &mut String, command: &str, output: &str) {
    let _ = write!(
        page,
        "\n```bash\n{command}\n```\n\n```text\n{}\n```\n",
        output.trim_end()
    );
}

/// A table of fields by name, in order.
fn table<'a>(page: &mut String, rows: impl IntoIterator<Item = (&'a str, &'a str)>) {
    page.push_str("\n| field | what it is |\n| --- | --- |\n");
    for (field, doc) in rows {
        let _ = writeln!(page, "| `{field}` | {} |", cell(doc));
    }
}

fn collections() -> String {
    let text = include_str!("../../../core/values/data/collections.md");
    let parts = parts(text);
    let part = |title: &str| {
        parts
            .iter()
            .find(|(t, _)| *t == title)
            .map(|(_, lines)| described(lines).into_iter().collect::<BTreeMap<_, _>>())
            .unwrap_or_else(|| panic!("collections.md has no `# {title}`"))
    };
    let (every, glossary) = (part("every record"), part("fields"));
    let groups: Vec<_> = parts
        .iter()
        .filter(|(title, _)| !matches!(*title, "every record" | "fields"))
        .map(|(title, lines)| (*title, entries(lines)))
        .collect();

    let mut page = header(
        "collections",
        "what a query can ask a note for. each collection is a list of records, \
         and each record a set of fields",
    );
    page.push_str(
        "\nname a collection in a query, filter it and pick fields, the same \
         language a note writes: `xmd weekend.x.md 'tasks | filter(fn(t) => !t.done) \
         | map(.title)'` for one note, `--workspace` for every note in a folder. \
         a feature module reads the same collections through its `inputs`. \
         [why xmd exists](../01-blog.md#ask-from-the-terminal) shows more. the examples \
         below run on [the examples](../../examples)\n\n## every record\n\n\
         most records have these fields, and each collection below adds its own\n",
    );
    table(&mut page, every.iter().map(|(f, d)| (*f, *d)));

    let examples = repo().join("examples");
    let names = bindings();
    let mut used: BTreeSet<String> = BTreeSet::new();
    let mut problems = Vec::new();
    let mut documented = Vec::new();
    for (group, (intro, collections)) in &groups {
        let _ = write!(page, "\n## {group}\n\n{}\n", intro.join("\n"));
        for (name, lines) in collections {
            documented.push(*name);
            if !names.iter().any(|n| n == name) {
                problems.push(format!("`{name}` is no collection a query can name"));
                continue;
            }
            let output = xmd(&examples, &["--workspace", name, "--json"]);
            let records: Vec<Value> = serde_json::from_str(&output)
                .unwrap_or_else(|e| panic!("`{name}` is not a JSON list: {e}"));
            let fields: BTreeSet<&str> = records
                .iter()
                .flat_map(|row| {
                    row.as_object()
                        .into_iter()
                        .flatten()
                        .map(|(f, _)| f.as_str())
                })
                .collect();
            let own: BTreeMap<_, _> = described(lines).into_iter().collect();
            for field in own.keys().filter(|f| !fields.contains(*f)) {
                problems.push(format!("{name} describes `{field}`, which no record has"));
            }
            let _ = write!(page, "\n### {name}\n\n{}\n", prose(lines).join("\n"));
            match keyed(lines, "example: ") {
                Some(command) => example(&mut page, command, &run(&examples, command)),
                None => problems.push(format!("{name} has no example")),
            }
            let mut rows = Vec::new();
            for field in &fields {
                let doc = own.get(field).or_else(|| {
                    used.insert(field.to_string());
                    if every.contains_key(field) {
                        None
                    } else {
                        glossary.get(field)
                    }
                });
                match doc {
                    Some(doc) => rows.push((*field, *doc)),
                    None if every.contains_key(field) => {}
                    None => problems.push(format!("{name}.{field} is not described")),
                }
            }
            if !rows.is_empty() {
                table(&mut page, rows);
            }
        }
    }
    for name in &names {
        if !documented.contains(&name.as_str()) {
            problems.push(format!("`{name}` has no entry"));
        }
    }
    for field in glossary.keys().filter(|f| !used.contains(**f)) {
        problems.push(format!(
            "`# fields` describes `{field}`, which no collection uses"
        ));
    }
    assert!(
        problems.is_empty(),
        "core/values/data/collections.md:\n{}",
        problems.join("\n")
    );
    page
}

fn writing_modules() -> String {
    use lang::eval::modules::{CompileModules, HOOK_RECORDS, HOOKS, ModuleRegistry, STEPS};
    use lang::stdlib::{CONTRACT, Role};

    let text = include_str!("../../../core/modules/data/kinds.md");
    let parts = parts(text);
    let (_, opening) = &parts[0];
    let (_, kinds) = entries(
        &parts
            .iter()
            .find(|(t, _)| *t == "kinds")
            .expect("# kinds")
            .1,
    );

    let mut page = header(
        "writing modules",
        "how to add to xmd with a module of your own: what each kind of module \
         is for, a working example of each, and what the host hands it",
    );
    let _ = write!(page, "\n{}\n", prose(opening).join("\n\n"));
    table(&mut page, described(opening));

    let mut shown = BTreeSet::new();
    for (kind, lines) in &kinds {
        let _ = write!(
            page,
            "\n## {kind} modules\n\n{}\n",
            prose(lines).join("\n\n")
        );
        let file = keyed(lines, "example: ").unwrap_or_else(|| panic!("{kind} has no example"));
        let path = repo().join(file);
        let source = std::fs::read_to_string(&path).unwrap();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        ModuleRegistry::compile(BTreeMap::from([(PathBuf::from(&name), source.clone())]))
            .unwrap_or_else(|e| panic!("the {kind} example {file} does not compile: {e}"));
        assert!(
            source.contains(&format!("kind: \"{kind}\"")),
            "the {kind} example {file} is another kind of module"
        );
        let _ = write!(
            page,
            "\n[{file}](../../{file}):\n\n```xmd\n{}\n```\n",
            source.trim_end()
        );
        if let Some(command) = keyed(lines, "run: ") {
            let output = run(path.parent().unwrap(), command);
            let _ = write!(
                page,
                "\n```bash\n{command}\n```\n\n```text\n{}\n```\n",
                output.trim_end()
            );
        }
        let hooks: Vec<_> = HOOKS
            .iter()
            .filter(|h| h.kinds.iter().any(|k| k.to_string() == *kind))
            .collect();
        if !hooks.is_empty() {
            let _ = write!(page, "\n### hooks\n");
            for hook in hooks {
                let _ = write!(
                    page,
                    "\n#### `{}({})`\n\nreturns {}\n\n{}\n",
                    hook.hook,
                    hook.params.join(", "),
                    hook.returns,
                    hook.doc
                );
            }
        }
        if let Some(records) = keyed(lines, "records: ") {
            let _ = write!(page, "\n### records\n");
            for name in records.split(", ") {
                let record = HOOK_RECORDS
                    .iter()
                    .find(|r| r.name == name)
                    .unwrap_or_else(|| panic!("hooks.md has no record `{name}`"));
                assert!(shown.insert(name), "`{name}` is shown under two kinds");
                let _ = write!(page, "\n#### {name}\n\n{}\n", record.doc);
                fields(&mut page, &record.fields);
            }
        }
        for protocol in STEPS.iter().filter(|p| p.kind.to_string() == *kind) {
            let limits = match protocol.kind.to_string().as_str() {
                "command" => format!(
                    "a step may request at most {} effects, and a run that has not \
                     finished in {} steps stops",
                    native::MAX_REQUESTS,
                    native::MAX_STEPS
                ),
                _ => format!(
                    "a lookup that has not finished in {} steps fails",
                    native::PROVIDER_STEPS
                ),
            };
            let _ = write!(
                page,
                "\n### the step loop\n\n{}\n\n{limits}\n",
                protocol.doc
            );
            for (title, list) in [("input", &protocol.input), ("output", &protocol.output)] {
                let _ = write!(page, "\n#### {title}\n");
                fields(&mut page, list);
            }
            let _ = write!(
                page,
                "\n#### effects\n\n| kind | request | answer | what it does |\n| --- | --- | --- | --- |\n"
            );
            for effect in &protocol.effects {
                let _ = writeln!(
                    page,
                    "| `{}` | {} | {} | {} |",
                    effect.kind,
                    cell(effect.request),
                    cell(effect.answer),
                    cell(effect.doc)
                );
            }
        }
    }
    for record in HOOK_RECORDS.iter() {
        assert!(
            shown.contains(record.name),
            "hooks.md's `{}` record is under no kind in kinds.md",
            record.name
        );
    }

    let (title, replacing) = parts
        .iter()
        .find(|(t, _)| *t == "replacing a bundled module")
        .expect("# replacing a bundled module");
    let _ = write!(page, "\n## {title}\n\n{}\n", prose(replacing).join("\n\n"));
    let mut modules: Vec<&str> = Vec::new();
    for entry in CONTRACT.iter() {
        if !modules.contains(&entry.module) {
            modules.push(entry.module);
        }
    }
    for module in modules {
        let _ = write!(
            page,
            "\n### {module}\n\n| function | returns | what it does | if it fails |\n| --- | --- | --- | --- |\n"
        );
        for entry in CONTRACT.iter().filter(|e| e.module == module) {
            let fails = match entry.role {
                Role::Presents { fallback } => format!("shows {fallback}"),
                Role::Decides => "reported".to_owned(),
            };
            let optional = if entry.required { "" } else { " (optional)" };
            let _ = writeln!(
                page,
                "| `{}({})`{optional} | {} | {} | {} |",
                entry.function,
                entry.params.join(", "),
                cell(entry.returns),
                cell(entry.doc),
                cell(&fails),
            );
        }
    }
    page
}

/// A table of `name: meaning` fields.
fn fields(page: &mut String, fields: &[&str]) {
    table(
        page,
        fields
            .iter()
            .map(|f| f.split_once(": ").expect("name: meaning")),
    );
}

/// Text in a table cell, its pipes escaped.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

fn xmd(root: &Path, args: &[&str]) -> String {
    let config = tempfile::tempdir().unwrap();
    let mut command = Command::new(env!("CARGO_BIN_EXE_xmd"));
    command.args(args).arg("--root").arg(root).current_dir(root);
    let output = support::isolate(&mut command, config.path(), support::NOW)
        .output()
        .unwrap();
    // `--help` takes no `--root`; its text comes back as an error then.
    let text = if output.status.success() {
        output.stdout
    } else {
        output.stderr
    };
    String::from_utf8(text).unwrap()
}

/// The bundled modules meet the whole stdlib contract: every module id it
/// names is bundled, and compiling the bundled set alone (which checks each
/// contract function's presence and arity) reports no problem.
#[test]
fn bundled_stdlib_meets_the_contract() {
    use lang::eval::modules::{CompileModules, ModuleRegistry};
    let registry = ModuleRegistry::compile(BTreeMap::new())
        .unwrap_or_else(|problems| panic!("the bundled stdlib breaks its contract:\n{problems}"));
    for entry in lang::stdlib::CONTRACT.iter() {
        let module = registry.get(entry.module).unwrap_or_else(|| {
            panic!(
                "the contract names '{}', which is not bundled",
                entry.module
            )
        });
        assert!(
            module
                .member_names()
                .iter()
                .any(|name| name == entry.function),
            "{}.{} is in the contract but not bundled",
            entry.module,
            entry.function
        );
    }
}
