[package]
name = "modules"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = { workspace = true }
common = { path = "../common" }
model = { path = "../model" }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
syntax = { path = "../syntax" }
url = { workspace = true }
values = { path = "../values" }

[lints]
workspace = true
