[package]
name = "model"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = { workspace = true }
common = { path = "../common" }
lsp-types = { workspace = true }
strum = { workspace = true }
syntax = { path = "../syntax" }
url = { workspace = true }

[lints]
workspace = true
