[package]
name = "eval"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = { workspace = true }
common = { path = "../common" }
model = { path = "../model" }
modules = { path = "../modules" }
serde = { workspace = true }
strum = { workspace = true }
syntax = { path = "../syntax" }
values = { path = "../values" }

[lints]
workspace = true
