[package]
name = "host"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
catalog = { path = "../catalog" }
chrono = { workspace = true }
feed-rs = "3"
ignore = "0.4"
lang = { path = "../../lang" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["process", "time"] }

[lints]
workspace = true
