[package]
name = "wtf"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[[bin]]
name = "wtf"
path = "src/main.rs"
required-features = ["native"]

[features]
default = ["native"]
native = ["dep:native"]
browser = ["dep:wasm"]

[dependencies]
common = { path = "common" }
features = { path = "features" }
model = { path = "model" }
native = { path = "native", optional = true }
wasm = { path = "wasm", optional = true }

[dev-dependencies]
lsp-types = { workspace = true }
serde_json = { workspace = true }
tempfile = "3"
url = { workspace = true }
