[package]
name = "native"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = { workspace = true }
clap = { version = "4", features = ["derive"] }
common = { path = "../../lang/core/common" }
eval = { path = "../../lang/core/eval" }
services = { path = "../../runtime/services", features = ["native"] }
host = { path = "../../runtime/host" }
lsp-types = { workspace = true }
model = { path = "../../lang/core/model" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std", "process", "time"] }
tower-lsp-server = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
