name = "WTF"
grammar = "markdown"
path_suffixes = ["wtf"]
block_comment = ["<!-- ", " -->"]
tab_size = 2
unordered_list = ["- ", "* ", "+ "]
task_list = { prefixes = ["- [ ] ", "- [x] ", "* [ ] ", "* [x] ", "+ [ ] ", "+ [x] "], continuation = "- [ ] " }
