[package]
name = "features"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
analysis = { path = "../analysis" }
chrono = { workspace = true }
lang = { path = "../../core" }
lsp-types = { workspace = true }
records = { path = "../records" }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
